### ISSUE TITLE
"This repo has some issues" Issue

### ISSUE THREAD

**Issue by bnb** [lockys/awesome-search#103]
Just discovered awesome-search today, and took a look at https://github.com/bnb/awesome-hyper. Noticed that there's a button at the top that says "This Repo Has Some Issues". Clicked it to see what it did, and it brought me here to create an issue 😅 

Wondering what the intent of this button is - does it lint the repo to check for errors? Just curious why it brought me to the AwesomeSearch repo's New Issue page. 😉 
![image](https://cloud.githubusercontent.com/assets/502396/21746221/b4db5b28-d50b-11e6-98ac-f06089f6486a.png)

**Comment by lockys** [comment]
@bnb
Thanks for filing this issue :) It's nice to see the awesome list maintainer here.
The main intent of this button is that I would like to know whether the Awesome Search parses or displays a specified awesome repo correctly, if not, users could just click the button to file an issue here directly.
I think it's not a good wording so that users may be confused. I am open to your opinion and PRs as well :)
